Quick reply and welcome message added
fossasia/susi_tweetbot pull request #22
Opened 2017-07-28 06:59 UTC by Manveer695

Fixes issue #17 i.e. to enable quick replies in SUSI Tweet bot.

Screenshots for the change: 
<img width="432" alt="twitterquick1" src="https://user-images.githubusercontent.com/20307535/28706040-2151f384-7390-11e7-8ce4-6da0ce7f0c76.PNG">
<img width="389" alt="twitterquickview" src="https://user-images.githubusercontent.com/20307535/28706108-73f0d5ba-7390-11e7-9bc6-75e7f08679c2.PNG">
<img width="380" alt="viewrepo1" src="https://user-images.githubusercontent.com/20307535/28706107-73f054e6-7390-11e7-8dde-f5e6d69fcdb7.PNG">

2017-07-28 07:00 UTC, Manveer695 commented
@AliAyub007 @chashmeetsingh @dynamitechetan @betterclever Please review! Thanks!

2017-07-29 16:06 UTC, betterclever approved these changes

2017-07-29 16:06 UTC, chashmeetsingh approved these changes

2017-07-29 16:20 UTC, mariobehling reviewed
Where does this message come from? All messages should be coming from the server and should be constituted as a skill.

The welcome message is erroneous and FOSSASIA is always spelled in capitals. (A pity you don't know that after several months of GSoC).

2017-07-29 16:21 UTC, mariobehling requested changes
Please ensure that messages come from the server. Also ensure correct spelling and grammar.

2017-07-30 16:15 UTC, Manveer695 commented
@mariobehling Made a [skill](https://github.com/fossasia/susi_skill_data/pull/257) in susi_skill_data repo, to get the answers from server for every query. Thank you, sir.

2017-07-31 12:28 UTC, mariobehling commented on index.js
> +			sendMessage(senderName, "Visit https://www.github.com/fossasia/susi_server");
Why is this hardcoded here?

2017-08-01 02:14 UTC, Manveer695 commented
@mariobehling Removed the hardcode, sir. Now, clicking on the View Repository button will redirect us directly to the SUSI server repository.

2017-08-03 09:19 UTC, mariobehling approved these changes

2017-08-03 09:19 UTC, mariobehling commented
Resolve conflicts!

2017-08-04 13:43 UTC, Manveer695 commented
@mariobehling Thanks a lot for the approved review. Resolved the conflicts, sir. Thank you.

2017-08-13 09:57 UTC, Manveer695 commented
@mariobehling Please merge it, sir. I need it for further work. Thank you.

2017-08-13 11:04 UTC, Manveer695 commented
@mariobehling Due to new PR's getting merged, conflicts arise in this PR. Please merge it, I need it for further work. Thank you.

2017-08-13 11:26 UTC, merged